#ifndef TK_ERROR_H
#define TK_ERROR_H

#define TK_AGENT_ERROR_DEFAULT										-5000
// util
#define TK_AGENT_ERROR_FAILED_MEMALLOC								-5001
#define TK_AGENT_ERROR_FAILED_REALLOC								-5002
#define TK_AGENT_ERROR_FAILED_BASE64ENCODE							-5003
#define TK_AGENT_ERROR_FALIED_BASE64DECODE							-5004
#define TK_AGENT_ERROR_FAILED_SETUSTRING							-5005
#define TK_AGENT_ERROR_FAILED_BIN2STR								-5006

// comm
#define TK_AGENT_ERROR_FAILED_COMM_INIT_SSL							-5100
#define TK_AGENT_ERROR_FAILED_COMM_INIT_SSLMETHOD					-5101
#define TK_AGENT_ERROR_FAILED_COMM_INIT_SSLCONTEXT					-5102
#define TK_AGENT_ERROR_FAILED_COMM_INIT_SSLCACERT					-5103
#define TK_AGENT_ERROR_FAILED_COMM_INIT_SSL_SETTIMEOUT				-5104

#define TK_AGENT_ERROR_FAILED_COMM_CONNECT_SSL_NEW					-5110
#define TK_AGENT_ERROR_FAILED_COMM_CONNECT_TCP_CONNECT				-5111
#define TK_AGENT_ERROR_FAILED_COMM_CONNECT_SSL_SETFD				-5112
#define TK_AGENT_ERROR_FAILED_COMM_CONNECT_SSL_CONNECT				-5113

#define TK_AGENT_ERROR_FAILED_COMM_DISCONNECT						-5120
#define TK_AGENT_ERROR_FAILED_COMM_SEND								-5130
#define TK_AGENT_ERROR_FAILED_COMM_RECV								-5140
#define TK_AGENT_ERROR_FAILED_COMM_FINAL							-5150
#define TK_AGENT_ERROR_FAILED_COMM_HTTP_RECV						-5160
#define TK_AGENT_ERROR_FAILED_COMM_SSL								-5170

// crypto
#define TK_AGENT_ERROR_FAILED_AES128_ENCRYPT_WC_SETKEY				-5200
#define TK_AGENT_ERROR_FAILED_AES128_ENCRYPT_WC_AES_CBCENCRYPT		-5201
#define TK_AGENT_ERROR_FAILED_AES128_ENCRYPT						-5202

#define TK_AGENT_ERROR_FAILED_AES128_DECRYPT_WC_AES_CBCDECRYPT		-5210
#define TK_AGENT_ERROR_FAILED_AES128_DECRYPT_PADDINGERROR			-5211
#define TK_AGENT_ERROR_FAILED_AES128_DECRYPT						-5212

#define TK_AGENT_ERROR_FAILED_MAKE_RANDOM_ARG_ERROR					-5220
#define TK_AGENT_ERROR_FAILED_MAKE_RANDOM_WC_INIT_RNG				-5221
#define TK_AGENT_ERROR_FAILED_MAKE_RANDOM_WC_RNG_GENBLOCK			-5222
#define TK_AGENT_ERROR_FAILED_MAKE_RANDOM_WC_FREE_RNG				-5223
#define TK_AGENT_ERROR_FAILED_MAKE_RANDOM							-5224

#define TK_AGENT_ERROR_FAILED_MAKE_HMAC_ARG_ERROR					-5230
#define TK_AGENT_ERROR_FAILED_MAKE_HMAC_INVALID_ALGO				-5231
#define TK_AGENT_ERROR_FAILED_MAKE_HMAC_WC_HMAC_SETKEY				-5232
#define TK_AGENT_ERROR_FAILED_MAKE_HMAC_WC_HMAC_UPDATE				-5233
#define TK_AGENT_ERROR_FAILED_MAKE_HMAC_WC_HMAC_FINAL				-5234
#define TK_AGENT_ERROR_FAILED_MAKE_HMAC								-5235

#define TK_AGENT_ERROR_FAILED_SHA256HASH_WC_SHA256					-5240
#define TK_AGENT_ERROR_FAILED_SHA256HASH							-5241

// keydb
#define TK_AGENT_ERROR_FAILED_SQLITE3_OPEN_V2						-5300
#define TK_AGENT_ERROR_FAILED_SQLITE3_SQLITE3_EXEC					-5301
#define TK_AGENT_ERROR_FAILED_SQLITE3_SQLITE3_PREPARE				-5302
#define TK_AGENT_ERROR_FAILED_SQLITE3								-5303

// protocolmanager
#define TK_AGENT_ERROR_FAILED_PARSEXML_EXPAT_PARSERCREATE			-5400
#define TK_AGENT_ERROR_FAILED_PARSEXML_EXPAT_PARSE					-5401

#define TK_AGENT_ERROR_FAILED_PARSENOXML							-5410
#define TK_AGENT_ERROR_FAILED_PARSENOXML_PARSE						-5411
#define TK_AGENT_ERROR_FAILED_PARSENOXML_INVALID_OPCODE				-5412

#define TK_AGENT_ERROR_FAILED_INDIRECT_MAKETLV_TOO_LONG_LENGTH		-5420

#define TK_AGENT_ERROR_FAILED_INDIRECT_PASETLV_INVALID_TAG			-5430
#define TK_AGENT_ERROR_FAILED_INDIRECT_PASETLV_TAG_NOT_FOUND		-5431


// keymanager (init)
#define TK_AGENT_ERROR_FAILED_SETCONFIG_ARG_ERROR					-5500
#define TK_AGENT_ERROR_FAILED_SETCONFIG_FILEOPEN					-5501

#define TK_AGENT_ERROR_FAILED_VERIFYAGENTHINT						-5510
#define TK_AGENT_ERROR_FAILED_VERIFYAGENTHINT_GETADAPTERSINFO		-5511
#define TK_AGENT_ERROR_FAILED_VERIFYAGENTHINT_INVALIDIP				-5512
#define TK_AGENT_ERROR_FAILED_VERIFYAGENTHINT_SOCKET				-5513
#define TK_AGENT_ERROR_FAILED_VERIFYAGENTHINT_IOCTL					-5514
#define TK_AGENT_ERROR_FAILED_VERIFYAGENTHINT_GETNAMEINFO			-5515

#define TK_AGENT_ERROR_FAILED_VERIFYINTEGRITY_VERIFY				-5520

#define TK_AGENT_ERROR_FAILED_CHECKCTX_INITIALIZE					-5530

// keymanager (getKey)
#define TK_AGENT_ERROR_FAILED_GETKEYFROMMEMORY_ARG_ERROR			-5600
#define TK_AGENT_ERROR_FAILED_GETKEYFROMMEMORY_NO_KEY				-5601
#define TK_AGENT_ERROR_FAILED_GETKEYFROMMEMORY_NOT_FOUND_KEYID		-5602

#define TK_AGENT_ERROR_FAILED_MAKE_KEYFROMMATERIAL_ARG_ERROR		-5610

#define TK_AGENT_ERROR_FAILED_CHECKKEYDBFILE_FILE_NOT_FOUND			-5620

#define TK_AGENT_ERROR_FAILED_MAKEREQUEST_INVALID_OPCODE			-5630

#define TK_AGENT_ERROR_FAILED_VERIFYKEYHMAC_ARG_ERROR				-5640
#define TK_AGENT_ERROR_FAILED_VERIFYKEYHMAC_VERIFY_ERROR			-5641

#define TK_AGENT_ERROR_FAILED_VALIDDATE_BEFORE						-5650
#define TK_AGENT_ERROR_FAILED_VALIDDATE_EXPIRED						-5651

#define TK_AGENT_ERROR_FAILED_EXPOSELEVEL							-5660
#define TK_AGENT_ERROR_FAILED_EXPOSELEVEL_UNDEFINED_KEYUSAGE		-5661
#define TK_AGENT_ERROR_FAILED_EXPOSELEVEL_SERVER_ONLY_KEY			-5662

#define TK_AGENT_ERROR_FAILED_REQUESTTOKMS_RESPONSE_MSG				-5670

// update
#define TK_AGENT_ERROR_FAILED_GET_UPDATEAVAILABLEKEYIDLIST_NOKEY	-5700

// indirect
#define TK_AGENT_ERROR_FAILED_INDIRECT_MAKERESPONSEKEYMSG_DYNAMIC	-5800

// Agent

#define TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_INIT_ARG_ERROR				-5900
#define TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_GETKEY_ARG_ERROR			-5901
#define TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_GETKEYALGO_ARG_ERROR		-5902
#define TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_GETKEYOPMODE_ARG_ERROR		-5903
#define TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_GETKEYINFO_ARG_ERROR		-5904
#define TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_GETENCKEY_ARG_ERROR			-5905
#define TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_GETENCKEYINFO_ARG_ERROR		-5906
#define TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_ENCRYPT_ARG_ERROR			-5907
#define TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_DECRYPT_ARG_ERROR			-5908
#define TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_IND_RESPONSE_ARG_ERROR		-5909
#define TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_IND_INIT_ARG_ERROR			-5910
#define TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_IND_GETKEY_ARG_ERROR		-5911
#define TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_IND_GETKEYALGO_ARG_ERROR	-5912
#define TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_IND_GETKEYOPMODE_ARG_ERROR	-5913
#define TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_IND_REQUEST_ARG_ERROR		-5914
#define TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_IND_SETKEY_ARG_ERROR		-5915

extern int	g_nAgentErrorCode;						// 직전 명령의 에러코드
extern char	g_szAgentErrorMsg[255 + 1];	// 직전 명령의 에러 메시지

typedef struct _errorString{
	int nErrorCode;
	char *szErrorStr;
}errorString;

static errorString g_errorString[] =
{
	{TK_AGENT_ERROR_DEFAULT									, "Error"},
	{TK_AGENT_ERROR_FAILED_MEMALLOC							, "[UTIL] Mem Alloc Error."},
	{TK_AGENT_ERROR_FAILED_REALLOC							, "[UTIL] Mem Realloc Error."},
	{TK_AGENT_ERROR_FAILED_BASE64ENCODE						, "[UTIL] Base64Encode Error."},
	{TK_AGENT_ERROR_FALIED_BASE64DECODE						, "[UTIL] Base64Decode Error."},
	{TK_AGENT_ERROR_FAILED_SETUSTRING						, "[UTIL] SetUString Error."},
	{TK_AGENT_ERROR_FAILED_BIN2STR							, "[UTIL] Bin2Str Error."},

	{TK_AGENT_ERROR_FAILED_COMM_INIT_SSL					, "[COMM Init] SSL Error."},
	{TK_AGENT_ERROR_FAILED_COMM_INIT_SSLMETHOD				, "[COMM Init] SSL Method Error."},
	{TK_AGENT_ERROR_FAILED_COMM_INIT_SSLCONTEXT				, "[COMM Init] SSL Context Error."},
	{TK_AGENT_ERROR_FAILED_COMM_INIT_SSLCACERT				, "[COMM Init] SSL CA Cert Load Error."},
	{TK_AGENT_ERROR_FAILED_COMM_INIT_SSL_SETTIMEOUT			, "[COMM Init] SSL Set Timeout Error."},
	

	{TK_AGENT_ERROR_FAILED_COMM_CONNECT_SSL_NEW				, "[COMM Connect] SSL New Error."},
	{TK_AGENT_ERROR_FAILED_COMM_CONNECT_TCP_CONNECT			, "[COMM Connect] TCP Connect Error."},
	{TK_AGENT_ERROR_FAILED_COMM_CONNECT_SSL_SETFD			, "[COMM Connect] SSL Set FD Error."},
	{TK_AGENT_ERROR_FAILED_COMM_CONNECT_SSL_CONNECT			, "[COMM Connect] SSL Connect Error."},

	{TK_AGENT_ERROR_FAILED_COMM_DISCONNECT						, "[COMM Connect] Disconnect Error."},
	{TK_AGENT_ERROR_FAILED_COMM_SEND							, "[COMM Send] Send Error."},
	{TK_AGENT_ERROR_FAILED_COMM_RECV							, "[COMM Recv] Recv Error."},
	{TK_AGENT_ERROR_FAILED_COMM_FINAL							, "[COMM Final] Final Error."},
	{TK_AGENT_ERROR_FAILED_COMM_HTTP_RECV						, "[COMM HTTP_Recv] Content-Length Not Found Error."},
	{TK_AGENT_ERROR_FAILED_COMM_SSL								, "[COMM SSL] This agent could not support SSL."},
	

	{TK_AGENT_ERROR_FAILED_AES128_ENCRYPT_WC_SETKEY				, "[Aes128 Encrypt] WC_SetKey Error."},
	{TK_AGENT_ERROR_FAILED_AES128_ENCRYPT_WC_AES_CBCENCRYPT		, "[Aes128 Encrypt] WC_Aes_CbcEncrypt Error."},
	{TK_AGENT_ERROR_FAILED_AES128_ENCRYPT						, "[Aes128 Encrypt] Encrypt Error."},

	{TK_AGENT_ERROR_FAILED_AES128_DECRYPT_WC_AES_CBCDECRYPT			, "[Aes128 Decrypt] WC_Aes_CbcDecrypt Error."},
	{TK_AGENT_ERROR_FAILED_AES128_DECRYPT_PADDINGERROR				, "[Aes128 Decrypt] Padding Error."},
	{TK_AGENT_ERROR_FAILED_AES128_DECRYPT							, "[Aes128 Decrypt] Decrypt Error."},

	{TK_AGENT_ERROR_FAILED_MAKE_RANDOM_ARG_ERROR				, "[Make Random] Arg Error."},
	{TK_AGENT_ERROR_FAILED_MAKE_RANDOM_WC_INIT_RNG				, "[Make Random] WC_Init_RNG Error."},
	{TK_AGENT_ERROR_FAILED_MAKE_RANDOM_WC_RNG_GENBLOCK			, "[Make Random] WC_RNG_GenBlock Error."},
	{TK_AGENT_ERROR_FAILED_MAKE_RANDOM_WC_FREE_RNG				, "[Make Random] WC_Free_Rng Error."},
	{TK_AGENT_ERROR_FAILED_MAKE_RANDOM							, "[Make Random] Random Error."},

	{TK_AGENT_ERROR_FAILED_MAKE_HMAC_ARG_ERROR				  	, "[Make HMAC] Arg Error."},
	{TK_AGENT_ERROR_FAILED_MAKE_HMAC_INVALID_ALGO			  	, "[Make HMAC] Invalid Algo Error."},
	{TK_AGENT_ERROR_FAILED_MAKE_HMAC_WC_HMAC_SETKEY			  	, "[Make HMAC] WC_HMAC_SetKey Error."},
	{TK_AGENT_ERROR_FAILED_MAKE_HMAC_WC_HMAC_UPDATE			  	, "[Make HMAC] WC_HMAC_Update Error."},
	{TK_AGENT_ERROR_FAILED_MAKE_HMAC_WC_HMAC_FINAL			  	, "[Make HMAC] WC_HMAC_Final Error."},
	{TK_AGENT_ERROR_FAILED_MAKE_HMAC						  	, "[Make HMAC] HMAC Error."},

	{TK_AGENT_ERROR_FAILED_SHA256HASH_WC_SHA256				   	, "[SHA256HASH] WC_SHA256 Error."},
	{TK_AGENT_ERROR_FAILED_SHA256HASH						   	, "[SHA256HASH] SHA256 Error."},

	{TK_AGENT_ERROR_FAILED_SQLITE3_OPEN_V2							, "[SQLITE3] Open_V2 Error."},
	{TK_AGENT_ERROR_FAILED_SQLITE3_SQLITE3_EXEC						, "[SQLITE3] SQLITE3_EXEC Error."},
	{TK_AGENT_ERROR_FAILED_SQLITE3_SQLITE3_PREPARE					, "[SQLITE3] SQLITE3_PREPARE Error."},
	{TK_AGENT_ERROR_FAILED_SQLITE3									, "[SQLITE3] SQLITE3 Error."},

	{TK_AGENT_ERROR_FAILED_PARSEXML_EXPAT_PARSERCREATE				, "[PARSEXML] Expat ParseCreate Error."},
	{TK_AGENT_ERROR_FAILED_PARSEXML_EXPAT_PARSE						, "[PARSEXML] Expat Parse Error."},

	{TK_AGENT_ERROR_FAILED_PARSENOXML								, "[PARSENOXML] ParseNoXml Error."},
	{TK_AGENT_ERROR_FAILED_PARSENOXML_PARSE							, "[PARSENOXML] Parse Error."},
	{TK_AGENT_ERROR_FAILED_PARSENOXML_INVALID_OPCODE				, "[PARSENOXML] Invalid OPCode Error."},

	{TK_AGENT_ERROR_FAILED_INDIRECT_MAKETLV_TOO_LONG_LENGTH			, "[INDIRECT_MAKETLV] Too Long Length Error."},

	{TK_AGENT_ERROR_FAILED_INDIRECT_PASETLV_INVALID_TAG				, "[INDIRECT_PASETLV] Invalid Tag Error."},
	{TK_AGENT_ERROR_FAILED_INDIRECT_PASETLV_TAG_NOT_FOUND			, "[INDIRECT_PASETLV] Tag Not Found Error."},


	{TK_AGENT_ERROR_FAILED_SETCONFIG_ARG_ERROR						, "[SETCONFIG] ARG Error."},
	{TK_AGENT_ERROR_FAILED_SETCONFIG_FILEOPEN						, "[SETCONFIG] File Open Error."},

	{TK_AGENT_ERROR_FAILED_VERIFYAGENTHINT						 	, "[VERIFYAGENTHINT] Verify Error."},
	{TK_AGENT_ERROR_FAILED_VERIFYAGENTHINT_GETADAPTERSINFO		 	, "[VERIFYAGENTHINT] GetAdaptersInfo Error."},
	{TK_AGENT_ERROR_FAILED_VERIFYAGENTHINT_INVALIDIP			 	, "[VERIFYAGENTHINT] Invalid IP Error."},
	{TK_AGENT_ERROR_FAILED_VERIFYAGENTHINT_SOCKET				 	, "[VERIFYAGENTHINT] socket Error."},
	{TK_AGENT_ERROR_FAILED_VERIFYAGENTHINT_IOCTL				 	, "[VERIFYAGENTHINT] ioctl Error."},
	{TK_AGENT_ERROR_FAILED_VERIFYAGENTHINT_GETNAMEINFO			 	, "[VERIFYAGENTHINT] GetNameInfo Error."},

	{TK_AGENT_ERROR_FAILED_VERIFYINTEGRITY_VERIFY				 	, "[VERIFYINTEGRITY_VERIFY] Verify Error."},

	{TK_AGENT_ERROR_FAILED_CHECKCTX_INITIALIZE					 	, "[CheckCTX] Init Error."},

	{TK_AGENT_ERROR_FAILED_GETKEYFROMMEMORY_ARG_ERROR			 	, "[GetKeyFromMemory] Arg Error."},
	{TK_AGENT_ERROR_FAILED_GETKEYFROMMEMORY_NO_KEY				 	, "[GetKeyFromMemory] No Key In Memory Error."},
	{TK_AGENT_ERROR_FAILED_GETKEYFROMMEMORY_NOT_FOUND_KEYID		 	, "[GetKeyFromMemory] Not Found Key ID Error."},

	{TK_AGENT_ERROR_FAILED_MAKE_KEYFROMMATERIAL_ARG_ERROR		 	, "[Make_KeyFromMaterial] Arg Error."},

	{TK_AGENT_ERROR_FAILED_CHECKKEYDBFILE_FILE_NOT_FOUND		 	, "[CheckKeyDBFile] File Not Found Error."},

	{TK_AGENT_ERROR_FAILED_MAKEREQUEST_INVALID_OPCODE			 	, "[MakeRequest] Invalid OPCode Error."},

	{TK_AGENT_ERROR_FAILED_VERIFYKEYHMAC_ARG_ERROR				 	, "[VerifyKeyHMAC] Arg Error."},
	{TK_AGENT_ERROR_FAILED_VERIFYKEYHMAC_VERIFY_ERROR			 	, "[VerifyKeyHMAC] Verify Error."},

	{TK_AGENT_ERROR_FAILED_VALIDDATE_BEFORE						 	, "[ValidDate] Key Use Date Not Yet Error."},
	{TK_AGENT_ERROR_FAILED_VALIDDATE_EXPIRED						, "[ValidDate] Key Use Date Expired Error."},

	{TK_AGENT_ERROR_FAILED_EXPOSELEVEL							 	, "[ExposeLevel] Expose Permission Denied Error."},
	{TK_AGENT_ERROR_FAILED_EXPOSELEVEL_UNDEFINED_KEYUSAGE		 	, "[ExposeLevel] Undefined Key Usage Error."},
	{TK_AGENT_ERROR_FAILED_EXPOSELEVEL_SERVER_ONLY_KEY			 	, "[ExposeLevel] Server Only Key Error."},
	{TK_AGENT_ERROR_FAILED_REQUESTTOKMS_RESPONSE_MSG			 	, "[RequestToKMS] Response Msg Error."},
	{TK_AGENT_ERROR_FAILED_GET_UPDATEAVAILABLEKEYIDLIST_NOKEY	 	, "[Get_UpdateAvailableKeyIDList] No key for update."},
	{TK_AGENT_ERROR_FAILED_INDIRECT_MAKERESPONSEKEYMSG_DYNAMIC	 	, "[Indirect_MakeResponseKeyMsg] Can't get dynamic key."},
	{TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_INIT_ARG_ERROR				, "[TrustKeystore_Init] Arg error."},
	{TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_GETKEY_ARG_ERROR			, "[TrustKeystore_GetKey] Arg error."},
	{TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_GETKEYALGO_ARG_ERROR		, "[TrustKeystore_GetKeyAlgo] Arg error."},
	{TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_GETKEYOPMODE_ARG_ERROR		, "[TrustKeystore_GetKeyOPMode] Arg error."},
	{TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_GETKEYINFO_ARG_ERROR		, "[TrustKeystore_GetKeyInfo] Arg error."},
	{TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_GETENCKEY_ARG_ERROR		, "[TrustKeystore_GetEncKey] Arg error."},
	{TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_GETENCKEYINFO_ARG_ERROR	, "[TrustKeystore_GetEncKeyInfo] Arg error."},	
	{TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_ENCRYPT_ARG_ERROR			, "[TrustKeystore_Encrypt] Arg error."},
	{TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_DECRYPT_ARG_ERROR			, "[TrustKeystore_Decrypt] Arg error."},
	{TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_IND_RESPONSE_ARG_ERROR		, "[TrustKeystore_Ind_Response] Arg error."},
	{TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_IND_INIT_ARG_ERROR			, "[TrustKeystore_Ind_Init] Arg error."},
	{TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_IND_GETKEY_ARG_ERROR		, "[TrustKeystore_Ind_Getkey] Arg error."},
	{TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_IND_GETKEYALGO_ARG_ERROR	, "[TrustKeystore_Ind_GetkeyAlgo] Arg error."},
	{TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_IND_GETKEYOPMODE_ARG_ERROR	, "[TrustKeystore_Ind_GetOPMode] Arg error."},
	{TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_IND_REQUEST_ARG_ERROR		, "[TrustKeystore_Ind_Request] Arg error."},
	{TK_AGENT_ERROR_FAILED_TRUSTKEYSTORE_IND_SETKEY_ARG_ERROR		, "[TrustKeystore_Ind_Setkey] Arg error."}
};

#endif //ERROR_H
